create table "public"."early_signups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "contact" text not null
);


alter table "public"."early_signups" enable row level security;

CREATE UNIQUE INDEX early_signups_contact_key ON public.early_signups USING btree (contact);

CREATE UNIQUE INDEX early_signups_pkey ON public.early_signups USING btree (id);

alter table "public"."early_signups" add constraint "early_signups_pkey" PRIMARY KEY using index "early_signups_pkey";

alter table "public"."early_signups" add constraint "early_signups_contact_key" UNIQUE using index "early_signups_contact_key";

grant delete on table "public"."early_signups" to "anon";

grant insert on table "public"."early_signups" to "anon";

grant references on table "public"."early_signups" to "anon";

grant select on table "public"."early_signups" to "anon";

grant trigger on table "public"."early_signups" to "anon";

grant truncate on table "public"."early_signups" to "anon";

grant update on table "public"."early_signups" to "anon";

grant delete on table "public"."early_signups" to "authenticated";

grant insert on table "public"."early_signups" to "authenticated";

grant references on table "public"."early_signups" to "authenticated";

grant select on table "public"."early_signups" to "authenticated";

grant trigger on table "public"."early_signups" to "authenticated";

grant truncate on table "public"."early_signups" to "authenticated";

grant update on table "public"."early_signups" to "authenticated";

grant delete on table "public"."early_signups" to "service_role";

grant insert on table "public"."early_signups" to "service_role";

grant references on table "public"."early_signups" to "service_role";

grant select on table "public"."early_signups" to "service_role";

grant trigger on table "public"."early_signups" to "service_role";

grant truncate on table "public"."early_signups" to "service_role";

grant update on table "public"."early_signups" to "service_role";

create policy "Disable delete access for all users"
on "public"."early_signups"
as permissive
for delete
to public
using (false);


create policy "Disable read access for all users"
on "public"."early_signups"
as permissive
for select
to public
using (false);


create policy "Enable write access for all users"
on "public"."early_signups"
as permissive
for insert
to public
with check (true);



